version: '3'
services:
  client:
    stdin_open: true
    build: ./client
    restart: always
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
  server:
    build: ./server
    restart: always
    command: yarn start
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
